version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    target-branch: "8.1.x"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    target-branch: "8.0.x"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "7.4.x"
    schedule:
      interval: "daily"
