language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - android-25
    - build-tools-25.0.0

install: ./gradlew assemble --stacktrace

script: ./gradlew check --info

deploy:
  provider: script
  script: ./gradlew clean publishPlugins -Pversion=$TRAVIS_TAG -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
  on:
    tags: true
