language: android
jdk:
  - openjdk8
  - openjdk11
sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29

install: ./gradlew clean -s

script: ./gradlew build -s

deploy:
  - provider: script
    script: ./gradlew publishPlugins -Pversion=$TRAVIS_TAG -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
    on:
      tags: true
      jdk: openjdk11
  - provider: script
    skip_cleanup: true
    script: "./gradlew uploadDocumentation"
    on:
      jdk: openjdk11
      tags: false
      all_branches: true
