plugins {
    id "io.freefair.settings.plugin-versions" version "9.0.0"
    id "com.gradle.develocity" version "4.2"
}

boolean isCiServer = System.getenv().containsKey("CI")

develocity {
    buildScan {
        publishing.onlyIf { isCiServer }
        termsOfUseUrl = "https://gradle.com/help/legal-terms-of-use"
        termsOfUseAgree = "yes"
    }
}
