name: Publish Release

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Publish package
        run: ./gradlew --no-parallel publishPlugins uploadDocumentation -Psigning.secretKeyRingFile=$GITHUB_WORKSPACE/secring.gpg -Psigning.password=$SIGNING_PASSWORD -Psigning.keyId=$SIGNING_KEY_ID
        env:
          SIGNING_KEY_ID: ${{ secrets.FREEFAIR_SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.FREEFAIR_SIGNING_PASSWORD }}
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          ORG_GRADLE_PROJECT_freefairDocsUser: ${{ secrets.FREEFAIR_DOCS_USER }}
          ORG_GRADLE_PROJECT_freefairDocsPass: ${{ secrets.FREEFAIR_DOCS_PASS }}
